import AuthGuard from "@/common/components/AuthGuard"
import LandingPage from "@/module/LandingPage"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import { HOME } from "@/common/constants"

export const metadata: Metadata = {
  title: `${HOME} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HomePage = () => {
  return (
    <AuthGuard>
      <LandingPage />
    </AuthGuard>
  )
}

export default HomePage
