import Home from "@/module/Home"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `Heim - Crypto Platform`,
  description: `Generated by Crypto Platform`,
}

const HomePage = () => {
  return <Home />
}

export default HomePage
