import Home from "@/module/Home"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `Home - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HomePage = () => {
  return (
    <Home />
  )
}

export default HomePage
